release:
  prerelease: false

builds:
  - binary: cloud-inventory
    env:
      - TOP=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# brews:
#   - github:
#       owner: msfidelis
#       name: homebrew-cloud-inventory
#     homepage: "https://github.com/msfidelis/cloud-inventory/"
#     description: "Validate SSL around web :spider:"

archives:
  - format: binary
    format_overrides:
      - goos: windows
        format: zip
